name: Build and Deploy
on: 
  push:
    branches:
      - main

jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3.5.2
        
      - name: Executing remote ssh commands using key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: raylison
          key: ${{ secrets.KEY }}
          script: |
            cd var/www/html/mr_moda_fitness/mr_moda_fitness
            git pull origin main
            make down
            make install
            make up   
        
